### ISSUE TITLE
BUG: Broken date in adi export

### ISSUE THREAD

**Issue by toddfoster** [k3ng/old_school_logger#1]
I entered a custom date when entering QSO's from last week. Date is correct in csv export, cut off in adi export (which adds another field). Looks like delimiters aren't accounted for.

The .adi exported by POTA has no delimiters in date or time fields.

CSV:
```
ID,Callsign,Frequency,Mode,Sent Report,Received Report,Date/Time,Note
1,KC3SJ,14034,CW,,,2024-12-08 21:46,FL US-10159
2,WS4Y,14058,CW,579,,2024-12-08 21:48,FL US-1873
```

ADI:
```
ADIF Export
<EOH>
<CALL:5>KC3SJ <FREQ:5>14034 <MODE:2>CW <RST_SENT:0> <RST_RCVD:0> <QSO_DATE:8>2024-12- <TIME_ON:2>08 <COMMENT:11>FL US-10159 <EOR>
<CALL:4>WS4Y <FREQ:5>14058 <MODE:2>CW <RST_SENT:3>579 <RST_RCVD:0> <QSO_DATE:8>2024-12- <TIME_ON:2>08 <COMMENT:10>FL US-1873 <EOR>
```

POTA example:
```
<ADIF_VER:5>3.1.2 
<PROGRAMID:4>POTA 
<PROGRAMVERSION:1>1 
<EOH>

<QSO_DATE:8>20241213 <TIME_ON:4>1222 <STATION_CALLSIGN:5>W2TEF <OPERATOR:5>W2TEF <CALL:4>NX3X <STATE:2>PA <BAND:3>40M <MODE:2>CW <MY_SIG:4>POTA <MY_SIG_INFO:8>US-11965 <MY_STATE:2>NJ <RST_SENT:3>599 <RST_RCVD:3>599 <EOR>
```

**Comment by k3ng** [comment]
Hi Todd,

Apologies for the problems.  I used AI to write that code and I assumed it "knew" how to properly format ADIF, and of course I didn't verify it.

Code updated, please test:  https://github.com/k3ng/old_school_logger/commit/ef90eb63058d166b2535e850bf47db58ed3b7f5a

73
Goody
K3NG
