### ISSUE TITLE
FEATURE: Consider accepting date/time without delimiters

### ISSUE THREAD

**Issue by toddfoster** [k3ng/old_school_logger#2]
When entering a date or time, you require delimiters. Consider making delimiters optional.

(Allowing a wide variety of input formats (8 Dec 2024, 12.22pm) opens up a whole can of worms. I wonder if there is an easy-to-use library that would do the parsing for you.)

```
> d 20241208
Error: Invalid date format. Use YYYY-MM-DD (e.g., 2024-11-24).
```

```
> t 1222
Error: Invalid time format. Use HH:MM or HH:MM:SS (e.g., 14:30 or 14:30:15).
```

**Comment by k3ng** [comment]
Hi Todd!  Great suggestion.  I have implemented in https://github.com/k3ng/old_school_logger/commit/42b4ed510bdad7b008ae69aae17d8236da6e8cb1 .

73
Goody
K3NG
